# golangci-lint configuration for GHCP Memory Context Server
run:
  timeout: 5m
  go: "1.22"
  skip-dirs:
    - vendor
    - .git
    - .taskmaster
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  # Security linter settings
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (we handle this case by case)

  # Code complexity
  gocyclo:
    min-complexity: 15

  # Line length
  lll:
    line-length: 120

  # Cognitive complexity
  gocognit:
    min-complexity: 20

  # Function length
  funlen:
    lines: 80
    statements: 40

  # Variable naming
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: exported
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: if-return
        severity: warning

linters:
  enable:
    # Security and vulnerability detection
    - gosec          # Security issues
    - govet          # Go vet checks
    - errcheck       # Unchecked errors
    - staticcheck    # Static analysis
    - ineffassign    # Ineffective assignments
    - unused         # Unused code

    # Code quality
    - gofmt          # Code formatting
    - goimports      # Import formatting
    - misspell       # Spelling mistakes
    - unconvert      # Unnecessary conversions
    - gocyclo        # Cyclomatic complexity
    - gocognit       # Cognitive complexity
    - funlen         # Function length
    - lll            # Line length

    # Best practices
    - revive         # Golint replacement
    - gocritic       # Go critique
    - prealloc       # Performance: prealloc slices

  disable:
    - exhaustive     # Can be too strict for some use cases
    - exhaustivestruct # Too strict for this project
    - forbidigo      # Not needed for this project
    - wsl            # Whitespace linter - too opinionated

issues:
  exclude-rules:
    # Disable some checks for test files
    - path: _test\.go
      linters:
        - gosec
        - funlen
        - gocognit

    # Disable line length for long URLs or strings
    - linters:
        - lll
      source: "^//.*http"

  max-issues-per-linter: 0
  max-same-issues: 0
