version: '3.8'

services:
  ghcp-memory-context:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcp-memory-context:latest
    container_name: ghcp-memory-context
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATA_DIR=/app/.memory-context
    volumes:
      - ./.memory-context:/app/.memory-context
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=ghcp-memory-context"
      - "description=Memory Context Server for GitHub Copilot Premium"

  # Optional: Redis for enhanced caching (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   container_name: ghcp-memory-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes

# volumes:
#   redis_data:

networks:
  default:
    name: ghcp-memory-network
